### PR TITLE
Materialized UI

### PR DESCRIPTION
**Pull request by manrajgrover**
Initial few changes

### CODE REVIEW

**Comment by sahildua2305** [comment]
What's the point of creating a PR when it's to be merged immediately without review or suggestions?

**Comment by manrajgrover** [comment]
These changes were reasonable to me considering the discussed between @ishan1604 and I. Also, these are not major changes that would break anything. This is mostly refactoring the code. Let me know if you have any objection.

**Comment by droidchef** [comment]
@ManrajGrover you have push rights to the repo, you can push the code directly too! If you are sending in a PR, let someone review it and then merge it :)

**Comment by manrajgrover** [comment]
@ishan1604 Works, will push directly from now on. :)

**Pull request merged**
